### ISSUE TITLE
Fail early on missing dependencies

### ISSUE THREAD

**Issue by tinuzz** [gary17/zfs-recompress#2]
I just tried your script for the first time. It looks very useful to me, thank you for writing it!

The script produces a lot of helpful output and tries to catch errors, which I like, but my first run still produced the following error for each file:

`zfs-recompress.sh: line 129: /usr/bin/uuidgen: No such file or directory`

I didn't check all the external executables that the script uses; I guess many are just available on a standard Linux system, but on Debian, 'uuidgen' is in the package 'uuid-runtime', which wasn't installed on my system.

Maybe you can test the existence (and/or executability) of the dependencies, and fail early if any of them are missing?

Cheers,
Martijn.

**Comment by gary17** [comment]
Good point, I'll look into this. In the meantime, it is possible to use the `--dry-run` flag to test script execution.

**Comment by gary17** [comment]
Fixed. Please give it a try sometime and let me know if there any problems with it.
