### ISSUE TITLE
Problems with whitespace in directory names

### ISSUE THREAD

**Issue by andrewluebke** [gary17/zfs-recompress#3]
If the directory name being recompressed has white space in it, i.e. Exchange Backup, the wrong free space is returned.  I'm using this on TrueNAS 12.  

Here is an example:

df -b "/mnt/DataPool/Exchange Backup"
DataPool/Exchange Backup 75847176184 6992391 75840183793     0%    /mnt/DataPool/Exchange Backup
df -b "/mnt/DataPool/Exchange Backup" | cut -w -f 4
Avail
6992392

Free space should be 75847176184 in this example.

**Comment by gary17** [comment]
Thank you for pointing this out. I will look into this.

**Comment by gary17** [comment]
Fixed. Please give it a try sometime and let me know if there any problems with it.

**Comment by andrewluebke** [comment]
Working now.  Thanks you very much!

**Comment by gary17** [comment]
Anytime.
