### ISSUE TITLE
Support wildcards

### ISSUE THREAD

**Issue by acsfer** [gary17/zfs-recompress#4]
Example:
`./zfs-recompress.sh --folder /datapool/users/*/files`

**Comment by gary17** [comment]
Thank you for the suggestion, but wildcarding a script with numerous file system operations might be a bit too risky. Perhaps, instead, something along the lines of: `for i in $(find /datapool/users/ -mindepth 1 -maxdepth 1 -type d); do ./zfs-recompress.sh --folder $i/files; done`?

**Comment by acsfer** [comment]
Yeah, this is exactly what I've done, but I've submitted it just in case ;)
Feel free to close.
