### ISSUE TITLE
Debian 10/11 doesn't works

### ISSUE THREAD

**Issue by openaspace** [gary17/zfs-recompress#5]
`root@osx1:/rpool_2tb/nas-file# sh ./zfs-recompress.sh
./zfs-recompress.sh: 253: declare: not found
./zfs-recompress.sh: 259: Syntax error: "(" unexpected (expecting "fi")`

**Comment by gary17** [comment]
`head -1 ./zfs-recompress.sh` says that this is a `bash` script, as opposed to an `sh` script. Please try `bash ./zfs-recompress.sh` or just `./zfs-recompress.sh`.

**Comment by openaspace** [comment]
'/usr/bin/uuidgen' is not executable or does not exist

**Comment by gary17** [comment]
https://command-not-found.com/uuidgen

**Comment by openaspace** [comment]
Really thank you

**Comment by gary17** [comment]
Anytime :).
